import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Providers from "@/components/Providers";
import { TooltipProvider } from "@/components/ui/Tooltip";
import { cn } from "@/libs/utils";

import "@/styles/globals.css";

import { type Metadata } from "next";
import { Calistoga, Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Akshay's Site",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "500", "600", "700"],
});
const calistoga = Calistoga({
  subsets: ["latin"],
  variable: "--font-serif",
  weight: ["400"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-background min-h-screen font-sans antialiased",
          inter.variable,
          calistoga.variable,
        )}
      >
        <Providers>
          <Header />
          <div className="mx-auto flex max-w-3xl flex-col px-8">
            <main className="grow">
              <TooltipProvider>{children}</TooltipProvider>
            </main>
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
